In [1]:
import pandas as pd

# Update de Centros

In [ ]:
contact = pd.read_csv('data/contacto.csv')
contact

In [ ]:
update = {'Centro' :  ['Alfredo Goyeneche', 'Aluche', 'Ángel Nieto', 'Blanca Fernández Ochoa', 'Casa de Campo',
                       'Centro Integrado Arganzuela', 'Ciudad de los Poetas', 'Daoíz y Velarde', 'El Espinillo', 'Entrevías',
                       'Estadio Vallehermoso', 'Eva Duarte', 'Faustina Valladolid', 'Fernando Martín', 'Gallur',
                       'Gimnasio Moscardó', 'José María Cagigal', 'La Bombilla', 'La Chopera', 'La Elipa',
                       'La Fundi', 'Luis Aragonés', 'Margot Moles', 'María Jesús Rosa', 'Marqués de Samaranch',
                       'Miguel Guillén Prim', 'Moratalaz', 'Orcasitas', 'Orcasur', 'Palomeras',
                       'Plata y Castañar', 'Playa Victoria', 'Pradillo', 'Pueblo Nuevo', 'Raúl González',
                       'San Blas', 'San Juan Bautista', 'Tenis Casa de Campo', 'Torrespaña', 'Triángulo de Oro',
                       'Vicente del Bosque','Victoria Hernández', 'Wilfred Agbonavbare'],
          'Distrito' : ['Moncloa-Aravaca', 'Latina', 'Puente de Vallecas', 'Carabanchel', 'Moncloa-Aravaca',
                        'Arganzuela', 'Moncloa-Aravaca', 'Retiro', 'Villaverde', 'Puente de Vallecas',
                        'Chamberí', 'Salamanca', 'Vicálvaro', 'Moncloa-Aravaca', 'Latina',
                        'Salamanca', 'Moncloa-Aravaca', 'Moncloa-Aravaca', 'Retiro', 'Moratalaz',
                        'Arganzuela', 'Hortaleza', 'Vicálvaro', 'Fuencarral-El Pardo', 'Arganzuela',
                        'Villa de Vallecas', 'Moratalaz', 'Usera', 'Usera', 'Puente de Vallecas',
                        'Villaverde', 'Tetuán', 'Chamartín', 'Ciudad Lineal', 'Villaverde',
                        'San Blas-Canillejas', 'Ciudad Lineal', 'Moncloa-Aravaca', 'Salamanca', 'Tetuán',
                        'Fuencarral-El Pardo', 'Villaverde', 'Puente de Vallecas'],
          'Teléfono' : [913571228, 917062868, 914781492, 914661278, 914630050,
                        915063616, 913732739, 914338950, 913603265, 917854214,
                        914804751, 913553201, 917723591, 914507344, 915251059,
                        913553201, 915413716, 917588677, 914201154, 914303511,
                        915288879, 913003612, 917769874, 914800476, 913642240,
                        913053451, 917727100, 914692374, 913171062, 917774901,
                        915051532, 915701841, 914137105, 913770251, 917953792,
                        913209818, 914164259, 914649617, 917654330, 915714117,
                        913147943, 913180857, 917854751]}

In [ ]:
df_update = pd.DataFrame(update)
df_update

In [ ]:
contact = pd.concat([contact, df_update])
contact

In [ ]:
contact = contact.reset_index().drop(columns='index')
contact

In [ ]:
contact = contact.sort_values(by='Centro')
contact

In [ ]:
contact.to_csv('data/contacto.csv', index=False)

# Update de CSVs

In [2]:
contacto = pd.read_csv('data/contacto.csv')
contacto.head()

                   Centro         Distrito   Telefono
0       Alfredo Goyeneche  Moncloa-Aravaca  913571228
1                  Aluche           Latina  917062868
2     Antonio Díaz Miguel           Tetuán  913145437
3                 Barajas          Barajas  913294219
4  Blanca Fernández Ochoa      Carabanchel  914661278

In [48]:
df = pd.read_csv('data/31-10-2023.csv').drop(columns=['Distrito', 'Telefono'])
df

,Fecha,Actividad,Horario,Rango_de_edad,Duracion,Centro,Direccion
0,2023-10-31,Gimnasia acuática,"19:30, 20:15",De 15 a 64 años,45 minutos,Alfredo Goyeneche,"Calle del Arroyo de Pozuelo, 99, 28023, Madrid"
1,2023-10-31,Combinada sala-piscina,19:15,De 15 a 64 años,60 minutos,Aluche,"Avenida de las Águilas, 14, 28044, Madrid"
2,2023-10-31,Correr por Madrid,19:30,De 15 a 64 años,90 minutos,Aluche,"Avenida de las Águilas, 14, 28044, Madrid"
3,2023-10-31,Cubo Gym Cross Training/Funcional,"18:15, 19:15",De 15 a 64 años,45 minutos,Aluche,"Avenida de las Águilas, 14, 28044, Madrid"
4,2023-10-31,Cuerpo mente,16:45,De 15 a 64 años,60 minutos,Aluche,"Avenida de las Águilas, 14, 28044, Madrid"
...,...,...,...,...,...,...,...
224,2023-10-31,Fitness,21:00,A partir de 15 años,60 minutos,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid"
225,2023-10-31,Gimnasia acuática,"20:15, 21:15",De 15 a 64 años,NaN,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid"
226,2023-10-31,Pilates acuático,19:15,A partir de 15 años,NaN,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid"
227,2023-10-31,Pilates MesD,19:00,A partir de 15 años,60 minutos,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid"
228,2023-10-31,Yoga,20:00,A partir de 15 años,NaN,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid"

In [49]:
df = pd.merge(df, contacto, on='Centro', how='inner')
df

,Fecha,Actividad,Horario,Rango_de_edad,Duracion,Centro,Direccion,Distrito,Telefono
0,2023-10-31,Gimnasia acuática,"19:30, 20:15",De 15 a 64 años,45 minutos,Alfredo Goyeneche,"Calle del Arroyo de Pozuelo, 99, 28023, Madrid",Moncloa-Aravaca,913571228
1,2023-10-31,Combinada sala-piscina,19:15,De 15 a 64 años,60 minutos,Aluche,"Avenida de las Águilas, 14, 28044, Madrid",Latina,917062868
2,2023-10-31,Correr por Madrid,19:30,De 15 a 64 años,90 minutos,Aluche,"Avenida de las Águilas, 14, 28044, Madrid",Latina,917062868
3,2023-10-31,Cubo Gym Cross Training/Funcional,"18:15, 19:15",De 15 a 64 años,45 minutos,Aluche,"Avenida de las Águilas, 14, 28044, Madrid",Latina,917062868
4,2023-10-31,Cuerpo mente,16:45,De 15 a 64 años,60 minutos,Aluche,"Avenida de las Águilas, 14, 28044, Madrid",Latina,917062868
...,...,...,...,...,...,...,...,...,...
224,2023-10-31,Fitness,21:00,A partir de 15 años,60 minutos,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid",Puente de Vallecas,917854751
225,2023-10-31,Gimnasia acuática,"20:15, 21:15",De 15 a 64 años,NaN,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid",Puente de Vallecas,917854751
226,2023-10-31,Pilates acuático,19:15,A partir de 15 años,NaN,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid",Puente de Vallecas,917854751
227,2023-10-31,Pilates MesD,19:00,A partir de 15 años,60 minutos,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid",Puente de Vallecas,917854751
228,2023-10-31,Yoga,20:00,A partir de 15 años,NaN,Wilfred Agbonavbare,"Calle Reguera de Tomateros, 39 B, 28053, Madrid",Puente de Vallecas,917854751

In [47]:
df.to_csv(f'data/revisado/{df.Fecha[0]}.csv', index=False)